/*
-- Query: SELECT * FROM nct.infrCodeGroup
LIMIT 0, 1000

-- Date: 2022-03-03 11:32
*/
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (1,NULL,'공통.디바이스',NULL,1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (2,NULL,'권한회원.역할',NULL,1,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (3,NULL,'회원.성별',NULL,1,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (4,NULL,'회원.보전기간',NULL,1,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (5,NULL,'회원.결혼여부',NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (6,NULL,'회원이메일.구분',NULL,1,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (7,NULL,'회원이메일.도메인',NULL,1,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (8,NULL,'회원전화.구분',NULL,1,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (9,NULL,'회원전화.장비',NULL,1,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (10,NULL,'회원전화.통신사',NULL,1,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (11,NULL,'회원주소온라인.구분',NULL,1,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (12,NULL,'회원주소온라인.sns구분',NULL,1,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (13,NULL,'회원취미.구분',NULL,1,13,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (14,NULL,'회원주소.구분',NULL,1,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ifcgSeq`,`ifcgSeqAnother`,`ifcgName`,`ifcgNameEng`,`ifcgUseNy`,`ifcgOrder`,`ifcgReferenceV1`,`ifcgReferenceV2`,`ifcgReferenceV3`,`ifcgReferenceI1`,`ifcgReferenceI2`,`ifcgReferenceI3`,`ifcgDesc`,`ifcgDelNy`,`regIp`,`regSeq`,`regDeviceCd`,`regDateTime`,`regDateTimeSvr`,`modIp`,`modSeq`,`modDeviceCd`,`modDateTime`,`modDateTimeSvr`) VALUES (15,NULL,'회원보안질문.구분',NULL,1,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
